version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=website/app.py
      - FLASK-ENV=development
    stdin_open: true
    tty: true